name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          echo "commit message: ${COMMIT_MESSAGE}"
        env: 
          COMMIT_MESSAGE: ${{ toJson(github.event.commits.*.message) }}

  print_date_job:
    runs-on: ubuntu-20.04
    steps:
      - name: "Now it is"
        run: |
          date

  print_directory_job:
    runs-on: ubuntu-20.04
    steps:
      - name: "Directory content"
        run: |
          ls -l
